package com.github.cms.bean;
// Generated 2014-9-10 14:52:54 by Hibernate Tools 3.2.2.GA



/**
 * Authorities generated by hbm2java
 */
public class Authorities  implements java.io.Serializable {


     private Integer id;
     public static final String ID = "id";
     private Users users;
     public static final String USERS = "users";
     private String authority;
     public static final String AUTHORITY = "authority";

    public Authorities() {
    }

    public Authorities(Users users, String authority) {
       this.users = users;
       this.authority = authority;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }




}


