package com.github.cms.bean;
// Generated 2014-8-28 15:00:48 by Hibernate Tools 3.2.2.GA



/**
 * Authorities generated by hbm2java
 */
public class Authorities  implements java.io.Serializable {


     private AuthoritiesId id;
     public static final String ID = "id";
     private Users users;
     public static final String USERS = "users";

    public Authorities() {
    }

    public Authorities(AuthoritiesId id, Users users) {
       this.id = id;
       this.users = users;
    }
   
    public AuthoritiesId getId() {
        return this.id;
    }
    
    public void setId(AuthoritiesId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


