package com.github.cms.bean;
// Generated 2014-8-29 15:40:16 by Hibernate Tools 3.2.2.GA



/**
 * GroupAuthorities generated by hbm2java
 */
public class GroupAuthorities  implements java.io.Serializable {


     private int id;
     public static final String ID = "id";
     private int groupId;
     public static final String GROUPID = "groupId";
     private String authority;
     public static final String AUTHORITY = "authority";

    public GroupAuthorities() {
    }

    public GroupAuthorities(int id, int groupId, String authority) {
       this.id = id;
       this.groupId = groupId;
       this.authority = authority;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }




}


