package com.github.cms.bean;
// Generated 2014-8-28 15:00:48 by Hibernate Tools 3.2.2.GA



/**
 * ModuleAuthorities generated by hbm2java
 */
public class ModuleAuthorities  implements java.io.Serializable {


     private ModuleAuthoritiesId id;
     public static final String ID = "id";

    public ModuleAuthorities() {
    }

    public ModuleAuthorities(ModuleAuthoritiesId id) {
       this.id = id;
    }
   
    public ModuleAuthoritiesId getId() {
        return this.id;
    }
    
    public void setId(ModuleAuthoritiesId id) {
        this.id = id;
    }




}


