package com.github.cms.bean;
// Generated 2014-8-29 15:40:16 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Modules generated by hbm2java
 */
public class Modules  implements java.io.Serializable {


     private Integer id;
     public static final String ID = "id";
     private String moduleId;
     public static final String MODULEID = "moduleId";
     private String title;
     public static final String TITLE = "title";
     private String parentId;
     public static final String PARENTID = "parentId";
     private String link;
     public static final String LINK = "link";
     private byte enabled;
     public static final String ENABLED = "enabled";
     private String note;
     public static final String NOTE = "note";
     private Date createtime;
     public static final String CREATETIME = "createtime";

    public Modules() {
    }

	
    public Modules(String moduleId, String title, String parentId, byte enabled) {
        this.moduleId = moduleId;
        this.title = title;
        this.parentId = parentId;
        this.enabled = enabled;
    }
    public Modules(String moduleId, String title, String parentId, String link, byte enabled, String note, Date createtime) {
       this.moduleId = moduleId;
       this.title = title;
       this.parentId = parentId;
       this.link = link;
       this.enabled = enabled;
       this.note = note;
       this.createtime = createtime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public byte getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(byte enabled) {
        this.enabled = enabled;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }




}


