package com.github.cms.bean;
// Generated 2014-8-26 16:09:34 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Modules generated by hbm2java
 */
public class Modules  implements java.io.Serializable {


     private String moduleId;
     private String title;
     private String parent;
     private String link;
     private byte enabled;
     private String note;
     private Date createtime;

    public Modules() {
    }

	
    public Modules(String moduleId, String title, String parent, byte enabled) {
        this.moduleId = moduleId;
        this.title = title;
        this.parent = parent;
        this.enabled = enabled;
    }
    public Modules(String moduleId, String title, String parent, String link, byte enabled, String note, Date createtime) {
       this.moduleId = moduleId;
       this.title = title;
       this.parent = parent;
       this.link = link;
       this.enabled = enabled;
       this.note = note;
       this.createtime = createtime;
    }
   
    public String getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getParent() {
        return this.parent;
    }
    
    public void setParent(String parent) {
        this.parent = parent;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public byte getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(byte enabled) {
        this.enabled = enabled;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }




}


