package com.github.cms.bean;
// Generated 2014-8-29 15:40:16 by Hibernate Tools 3.2.2.GA



/**
 * ModuleAuthorities generated by hbm2java
 */
public class ModuleAuthorities  implements java.io.Serializable {


     private Integer id;
     public static final String ID = "id";
     private int moduleId;
     public static final String MODULEID = "moduleId";
     private String authority;
     public static final String AUTHORITY = "authority";

    public ModuleAuthorities() {
    }

    public ModuleAuthorities(int moduleId, String authority) {
       this.moduleId = moduleId;
       this.authority = authority;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }




}


